# SPDX-FileCopyrightText: 2026 Johan Louwers <louwersj@gmail.com>
# SPDX-License-Identifier: Apache-2.0

"""Synthetic testing helpers for nats-sinks maintainers and integrators.

The objects exported here are intentionally safe for public test evidence.
They generate fake `NatsEnvelope` instances and sanitized reports that exercise
mission-style metadata without requiring real operational subjects, payloads,
credentials, or infrastructure locators.
"""

from nats_sinks.testing.fanout_certification import (
    FanoutAckProbe,
    FanoutCertificationCase,
    FanoutCertificationResult,
    FanoutOperationPlan,
    certify_fanout_ack_order,
    certify_fanout_route_selection,
    fanout_certification_envelope,
    fanout_certification_policy,
)
from nats_sinks.testing.load_profile import (
    LoadPhaseTiming,
    LoadProfileOptions,
    LoadProfileReport,
    render_load_profile_report,
    run_load_profile,
)
from nats_sinks.testing.oracle_benchmark import (
    BenchmarkPhaseTiming,
    OracleBenchmarkOptions,
    OracleBenchmarkReport,
    build_oracle_benchmark_report,
    render_oracle_benchmark_report,
    sanitize_public_text,
)
from nats_sinks.testing.sink_certification import (
    SinkCertificationCase,
    assert_envelope_has_no_ack_primitives,
    assert_log_records_exclude_sensitive_values,
    assert_sink_protocol_boundary,
    certification_envelope,
    certify_sink_duplicate_redelivery,
    certify_sink_lifecycle,
    certify_sink_write_success,
)
from nats_sinks.testing.subject_observability_certification import (
    SUBJECT_OBSERVABILITY_ALLOWED_LABEL,
    SUBJECT_OBSERVABILITY_OVERFLOW_LABEL,
    SUBJECT_OBSERVABILITY_RAW_SUBJECTS,
    SubjectObservabilityCertificationReport,
    SubjectObservabilityDeliveryProbe,
    assert_subject_observability_output_is_sanitized,
    certify_subject_observability_delivery_non_interference,
    certify_subject_observability_malformed_policy_rejection,
    render_subject_observability_connector_outputs,
    run_subject_observability_certification,
    subject_observability_certification_envelopes,
    subject_observability_certification_policy,
    subject_observability_certification_snapshot,
    subject_observability_fail_closed_policy,
    subject_observability_overflow_policy,
)
from nats_sinks.testing.synthetic import (
    SyntheticFileSinkResult,
    SyntheticMessage,
    SyntheticScenarioProfile,
    SyntheticScenarioReport,
    generate_synthetic_scenario,
    render_synthetic_report_markdown,
    run_file_sink_synthetic_scenario,
    synthetic_report,
)
from nats_sinks.testing.websocket_harness import (
    WebSocketHarnessConfig,
    WebSocketHarnessPorts,
    choose_loopback_port,
    choose_websocket_harness_ports,
    nats_server_command,
    port_is_available,
    render_nats_websocket_config,
    sanitized_selected_ports,
    wait_for_tcp_port,
    write_nats_websocket_config,
)

__all__ = [
    "SUBJECT_OBSERVABILITY_ALLOWED_LABEL",
    "SUBJECT_OBSERVABILITY_OVERFLOW_LABEL",
    "SUBJECT_OBSERVABILITY_RAW_SUBJECTS",
    "BenchmarkPhaseTiming",
    "FanoutAckProbe",
    "FanoutCertificationCase",
    "FanoutCertificationResult",
    "FanoutOperationPlan",
    "LoadPhaseTiming",
    "LoadProfileOptions",
    "LoadProfileReport",
    "OracleBenchmarkOptions",
    "OracleBenchmarkReport",
    "SinkCertificationCase",
    "SubjectObservabilityCertificationReport",
    "SubjectObservabilityDeliveryProbe",
    "SyntheticFileSinkResult",
    "SyntheticMessage",
    "SyntheticScenarioProfile",
    "SyntheticScenarioReport",
    "WebSocketHarnessConfig",
    "WebSocketHarnessPorts",
    "assert_envelope_has_no_ack_primitives",
    "assert_log_records_exclude_sensitive_values",
    "assert_sink_protocol_boundary",
    "assert_subject_observability_output_is_sanitized",
    "build_oracle_benchmark_report",
    "certification_envelope",
    "certify_fanout_ack_order",
    "certify_fanout_route_selection",
    "certify_sink_duplicate_redelivery",
    "certify_sink_lifecycle",
    "certify_sink_write_success",
    "certify_subject_observability_delivery_non_interference",
    "certify_subject_observability_malformed_policy_rejection",
    "choose_loopback_port",
    "choose_websocket_harness_ports",
    "fanout_certification_envelope",
    "fanout_certification_policy",
    "generate_synthetic_scenario",
    "nats_server_command",
    "port_is_available",
    "render_load_profile_report",
    "render_nats_websocket_config",
    "render_oracle_benchmark_report",
    "render_subject_observability_connector_outputs",
    "render_synthetic_report_markdown",
    "run_file_sink_synthetic_scenario",
    "run_load_profile",
    "run_subject_observability_certification",
    "sanitize_public_text",
    "sanitized_selected_ports",
    "subject_observability_certification_envelopes",
    "subject_observability_certification_policy",
    "subject_observability_certification_snapshot",
    "subject_observability_fail_closed_policy",
    "subject_observability_overflow_policy",
    "synthetic_report",
    "wait_for_tcp_port",
    "write_nats_websocket_config",
]
