#!/usr/bin/env sh
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Johan Louwers <louwersj@gmail.com>

set -eu

# This entrypoint is intentionally test-only. It initializes a fresh Oracle
# MySQL data directory, creates a bounded local test account, and then starts
# Oracle MySQL in the foreground. The root and application passwords must be
# supplied through mounted secret files generated by the smoke runner.

DATA_DIR="/var/lib/mysql"
RUN_DIR="/run/mysqld"
SOCKET="${ORACLE_MYSQL_SOCKET:-/run/mysqld/mysql.sock}"
PORT="${ORACLE_MYSQL_PORT:-3306}"
DATABASE="${ORACLE_MYSQL_TEST_DATABASE:-nats_sinks_test}"
APP_USER="${ORACLE_MYSQL_TEST_USER:-nats_sinks_test}"
ROOT_PASSWORD_FILE="${ORACLE_MYSQL_ROOT_PASSWORD_FILE:-/run/secrets/oracle-mysql-root-password}"
APP_PASSWORD_FILE="${ORACLE_MYSQL_APP_PASSWORD_FILE:-/run/secrets/oracle-mysql-app-password}"

fail() {
  printf 'Oracle MySQL test container startup failed: %s\n' "$1" >&2
  exit 1
}

read_secret_file() {
  secret_path="$1"
  [ -f "$secret_path" ] || fail "required secret file is missing"
  secret_value="$(tr -d '\r\n' < "$secret_path")"
  case "$secret_value" in
    (*[!A-Za-z0-9_-]*|'')
      fail "secret file contains an unsupported value"
      ;;
  esac
  secret_length=${#secret_value}
  if [ "$secret_length" -lt 24 ] || [ "$secret_length" -gt 256 ]; then
    fail "secret file value length is outside the supported range"
  fi
  printf '%s' "$secret_value"
}

wait_for_socket() {
  attempts=0
  while [ "$attempts" -lt 120 ]; do
    if mysqladmin --protocol=socket --socket="$SOCKET" --user=root ping >/dev/null 2>&1; then
      return 0
    fi
    attempts=$((attempts + 1))
    sleep 1
  done
  return 1
}

shutdown_bootstrap() {
  MYSQL_PWD="$ROOT_PASSWORD" mysqladmin --protocol=socket --socket="$SOCKET" --user=root shutdown >/dev/null 2>&1 || true
}

ROOT_PASSWORD="$(read_secret_file "$ROOT_PASSWORD_FILE")"
APP_PASSWORD="$(read_secret_file "$APP_PASSWORD_FILE")"

mkdir -p "$DATA_DIR" "$RUN_DIR"
chown -R mysql:mysql "$DATA_DIR" "$RUN_DIR"
chmod 0750 "$DATA_DIR" "$RUN_DIR"

if [ ! -d "$DATA_DIR/mysql" ]; then
  if ! mysqld --initialize-insecure \
      --user=mysql \
      --datadir="$DATA_DIR" \
      --log-error=/tmp/oracle-mysql-initialize.err \
      >/tmp/oracle-mysql-initialize.log 2>&1; then
    tail -n 80 /tmp/oracle-mysql-initialize.log >&2 || true
    tail -n 80 /tmp/oracle-mysql-initialize.err >&2 || true
    fail "Oracle MySQL data directory initialization failed"
  fi
fi

mysqld \
  --user=mysql \
  --datadir="$DATA_DIR" \
  --socket="$SOCKET" \
  --pid-file="$RUN_DIR/mysqld-bootstrap.pid" \
  --skip-networking \
  --skip-name-resolve \
  --log-error=/tmp/oracle-mysql-bootstrap.err &

BOOTSTRAP_PID="$!"

if ! wait_for_socket; then
  tail -n 80 /tmp/oracle-mysql-bootstrap.err >&2 || true
  kill "$BOOTSTRAP_PID" >/dev/null 2>&1 || true
  fail "Oracle MySQL bootstrap server did not become ready"
fi

mysql --protocol=socket --socket="$SOCKET" --user=root <<SQL
ALTER USER 'root'@'localhost' IDENTIFIED BY '${ROOT_PASSWORD}';
CREATE DATABASE IF NOT EXISTS \`${DATABASE}\`;
CREATE USER IF NOT EXISTS '${APP_USER}'@'%' IDENTIFIED BY '${APP_PASSWORD}';
ALTER USER '${APP_USER}'@'%' IDENTIFIED BY '${APP_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DATABASE}\`.* TO '${APP_USER}'@'%';
FLUSH PRIVILEGES;
SQL

shutdown_bootstrap
wait "$BOOTSTRAP_PID" >/dev/null 2>&1 || true

exec mysqld \
  --user=mysql \
  --datadir="$DATA_DIR" \
  --socket="$SOCKET" \
  --pid-file="$RUN_DIR/mysqld.pid" \
  --bind-address=0.0.0.0 \
  --port="$PORT" \
  --skip-name-resolve \
  --local-infile=0 \
  --symbolic-links=0 \
  --secure-file-priv=NULL \
  --log-error=/tmp/oracle-mysql.err
