# SPDX-FileCopyrightText: 2026 Johan Louwers <louwersj@gmail.com>
# SPDX-License-Identifier: Apache-2.0

"""Generate pip requirements manifests for GitHub's Dependency Graph.

`pyproject.toml` remains the authoritative Python package definition for this
project. GitHub's Dependency Graph has the broadest Python/pip support for
`requirements.txt` style manifests, so this script derives those manifests from
`pyproject.toml` and lets CI fail if they drift.

The files generated here are intentionally not lock files. They mirror the
version ranges published by the package metadata so Dependabot and the
Dependency Graph can see the direct runtime and optional dependency surface.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = ROOT / "pyproject.toml"

HEADER = (
    "# This file is generated by scripts/update-dependency-manifests.py.",
    "# Do not edit by hand; edit pyproject.toml and rerun the generator.",
)

EXTRA_MANIFESTS = {
    "crypto": "requirements-crypto.txt",
    "oracle": "requirements-oracle.txt",
    "test": "requirements-test.txt",
    "dev": "requirements-dev.txt",
    "docs": "requirements-docs.txt",
    "all": "requirements-all.txt",
}


def _load_pyproject() -> dict[str, object]:
    with PYPROJECT.open("rb") as file_obj:
        return tomllib.load(file_obj)


def _project_table(pyproject: dict[str, object]) -> dict[str, object]:
    project = pyproject.get("project")
    if not isinstance(project, dict):
        raise SystemExit("pyproject.toml does not contain a [project] table.")
    return project


def _string_list(value: object, *, name: str) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise SystemExit(f"{name} must be a list of strings.")
    return value


def _optional_dependencies(project: dict[str, object]) -> dict[str, list[str]]:
    raw_optional = project.get("optional-dependencies", {})
    if not isinstance(raw_optional, dict):
        raise SystemExit("[project.optional-dependencies] must be a table.")

    result: dict[str, list[str]] = {}
    for name, value in raw_optional.items():
        if not isinstance(name, str):
            raise SystemExit("Optional dependency group names must be strings.")
        result[name] = _string_list(value, name=f"optional dependency group {name!r}")
    return result


def _expand_self_reference(
    requirement: str,
    optional: dict[str, list[str]],
    *,
    seen: set[str],
) -> list[str]:
    """Expand entries such as ``nats-sinks[crypto,oracle]`` for manifest files.

    The package's `all` extra references this project with other extras. That
    is valid package metadata, but it is not helpful in a generated
    requirements manifest for dependency graphing because the graph should see
    the actual optional dependencies. This small parser handles only the local
    self-reference shape used by this project and leaves every other
    requirement untouched.
    """

    prefix = "nats-sinks["
    if not requirement.startswith(prefix) or not requirement.endswith("]"):
        return [requirement]

    inner = requirement[len(prefix) : -1]
    expanded: list[str] = []
    for extra_name in (part.strip() for part in inner.split(",")):
        if not extra_name:
            continue
        if extra_name in seen:
            raise SystemExit(f"Recursive optional dependency reference: {extra_name}")
        if extra_name not in optional:
            raise SystemExit(f"Unknown optional dependency group referenced by {requirement!r}.")
        expanded.extend(
            _expand_requirements(optional[extra_name], optional, seen=seen | {extra_name})
        )
    return expanded


def _expand_requirements(
    requirements: Iterable[str],
    optional: dict[str, list[str]],
    *,
    seen: set[str] | None = None,
) -> list[str]:
    active_seen = seen or set()
    expanded: list[str] = []
    for requirement in requirements:
        expanded.extend(_expand_self_reference(requirement, optional, seen=active_seen))
    return _dedupe(expanded)


def _dedupe(requirements: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for requirement in requirements:
        normalized = requirement.strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        result.append(normalized)
    return result


def _render_manifest(title: str, requirements: Iterable[str], *, include_runtime: bool) -> str:
    lines = [*HEADER, f"# {title}", ""]
    if include_runtime:
        lines.extend(["-r requirements.txt", ""])
    lines.extend(requirements)
    return "\n".join(lines) + "\n"


def _expected_manifests() -> dict[Path, str]:
    project = _project_table(_load_pyproject())
    runtime = _string_list(project.get("dependencies", []), name="project.dependencies")
    optional = _optional_dependencies(project)

    manifests = {
        ROOT / "requirements.txt": _render_manifest(
            "Runtime dependencies published by the nats-sinks package.",
            runtime,
            include_runtime=False,
        )
    }

    for extra_name, filename in EXTRA_MANIFESTS.items():
        if extra_name not in optional:
            raise SystemExit(f"Missing optional dependency group {extra_name!r}.")
        requirements = _expand_requirements(optional[extra_name], optional, seen={extra_name})
        manifests[ROOT / filename] = _render_manifest(
            f"Runtime dependencies plus the {extra_name!r} optional dependency group.",
            requirements,
            include_runtime=True,
        )

    return manifests


def _write_or_check(*, check: bool) -> int:
    mismatched: list[Path] = []
    for path, expected in _expected_manifests().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        if check:
            mismatched.append(path)
            continue
        path.write_text(expected, encoding="utf-8")
        sys.stdout.write(f"wrote {path.relative_to(ROOT)}\n")

    if mismatched:
        joined = ", ".join(str(path.relative_to(ROOT)) for path in mismatched)
        sys.stderr.write(
            "Dependency manifest files are out of date. "
            "Run: python scripts/update-dependency-manifests.py\n"
        )
        sys.stderr.write(f"Out-of-date files: {joined}\n")
        return 1

    if check:
        sys.stdout.write("Dependency manifest files are up to date.\n")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or check dependency manifests derived from pyproject.toml."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated manifests differ from the committed files.",
    )
    args = parser.parse_args()
    return _write_or_check(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
