# SPDX-FileCopyrightText: 2026 Johan Louwers <louwersj@gmail.com>
# SPDX-License-Identifier: Apache-2.0

"""Public API compatibility checks for documented import paths.

These tests are intentionally small but important.  README examples,
documentation snippets, and PyPI users depend on import paths staying stable
while the project evolves internally.  The contract below is therefore a
release guard: adding a new public symbol is easy, but removing or moving an
existing documented symbol should be treated as a compatibility decision.
"""

from __future__ import annotations

import importlib
import tomllib
from pathlib import Path
from typing import Any, cast

import typer

import nats_sinks
from nats_sinks import (
    JetStreamSinkRunner as ReadmeJetStreamSinkRunner,
)
from nats_sinks import (
    NatsEnvelope as ReadmeNatsEnvelope,
)
from nats_sinks import (
    Sink as ReadmeSink,
)
from nats_sinks.coherence import CoherenceSink as ReadmeCoherenceSink
from nats_sinks.file import FileSink as ReadmeFileSink
from nats_sinks.mysql import MySqlSink as ReadmeMySqlSink
from nats_sinks.oracle import OracleSink as ReadmeOracleSink
from nats_sinks.oracle_nosql import OracleNoSqlSink as ReadmeOracleNoSqlSink
from nats_sinks.spool import SpoolSink as ReadmeSpoolSink

PUBLIC_API_CONTRACT: dict[str, tuple[str, ...]] = {
    "nats_sinks": (
        "AckError",
        "ConfigurationError",
        "ConsumerDrift",
        "ConsumerManagementConfig",
        "ConsumerManagementResult",
        "CoherenceSink",
        "CoherenceSinkConfig",
        "CUSTODY_SCHEMA",
        "CUSTODY_SUPPORTED_ALGORITHMS",
        "CustodyConfig",
        "DeadLetterError",
        "DestinationUnavailableError",
        "EncryptionConfig",
        "EncryptionRuleConfig",
        "FANOUT_OPTIONAL_ACK_DEFAULTS",
        "FanoutAckGateError",
        "FanoutAckGateResult",
        "FanoutRequiredSinkError",
        "FanoutSink",
        "FanoutTargetResult",
        "FileSink",
        "FlushableSink",
        "HealthCheckableSink",
        "InMemoryMetrics",
        "JetStreamAdvisory",
        "JetStreamAdvisoryConfig",
        "JetStreamAdvisoryMonitor",
        "JetStreamSinkRunner",
        "JsonFileMetrics",
        "MESSAGE_AUTHENTICITY_SCHEMA",
        "MessageAuthenticityConfig",
        "MessageAuthenticityEvaluation",
        "MessageAuthenticityRuleConfig",
        "MessageAuthenticityViolation",
        "MessageMetadataConfig",
        "MessageMetadataFieldConfig",
        "MessageMetadataLabelsConfig",
        "MessageMetadataRuleConfig",
        "MetricsConfig",
        "MetricNames",
        "MissionMetadataConfig",
        "MissionMetadataRuleConfig",
        "NatsEnvelope",
        "NatsSinksError",
        "NoopMetrics",
        "NormalizedPayload",
        "OracleNoSqlSink",
        "OracleNoSqlSinkConfig",
        "PayloadEncryptor",
        "PayloadKeyRegistry",
        "PermanentSinkError",
        "PolicyEvaluation",
        "PolicyViolation",
        "PolicyViolationError",
        "PreSinkPolicyConfig",
        "PreSinkPolicyRuleConfig",
        "PushConsumerCapabilityResult",
        "PushConsumerConfig",
        "RouteHeaderMatchConfig",
        "RouteMatchConfig",
        "RoutePolicyRouteConfig",
        "RouteSelection",
        "RouteTargetConfig",
        "RoutingMatchPolicyConfig",
        "SINK_CONNECTOR_API_VERSION",
        "SINK_CONNECTOR_ENTRY_POINT_GROUP",
        "SECURITY_LABEL_PROFILE_NAME",
        "SchemaAwareSink",
        "SerializationError",
        "Sink",
        "SinkConnector",
        "SinkConnectorStatus",
        "SinkError",
        "SinkPluginConfig",
        "SizePolicyConfig",
        "SizePolicyEvaluation",
        "SizePolicyViolation",
        "SizePolicyViolationError",
        "SpoolReplayResult",
        "SpoolSink",
        "SpoolSinkConfig",
        "SUPPORTED_MESSAGE_AUTHENTICITY_ALGORITHMS",
        "SubjectPayloadEncryptor",
        "TemporarySinkError",
        "ValidationError",
        "advisory_kind_from_subject",
        "attach_custody_metadata",
        "build_consumer_config",
        "build_push_consumer_config",
        "build_nats_metadata_snapshot",
        "canonical_json_bytes",
        "canonical_message_authenticity_bytes",
        "canonical_message_authenticity_document",
        "compute_custody_metadata",
        "detect_consumer_drift",
        "detect_push_consumer_capabilities",
        "detect_push_consumer_drift",
        "datetime_to_epoch_ns",
        "decrypt_payload",
        "ensure_jetstream_consumer",
        "ensure_jetstream_push_consumer",
        "evaluate_pre_sink_policy",
        "evaluate_message_authenticity",
        "evaluate_size_policy",
        "hmac_sha256_signature_b64",
        "is_encrypted_payload_envelope",
        "load_entry_point_connectors",
        "load_metrics_snapshot",
        "metric_rows_from_snapshot",
        "normalize_connector_name",
        "normalize_payload_for_json_storage",
        "observe_jetstream_advisory_message",
        "parse_jetstream_advisory",
        "parse_mission_metadata_header",
        "parse_security_label_header",
        "qualified_metric_name",
        "replay_spool_to_sink",
        "route_matches_envelope",
        "select_route_targets",
        "validate_advisory_subject",
        "validate_push_consumer_capabilities",
        "wait_for_fanout_ack_gate",
        "write_metrics_snapshot",
    ),
    "nats_sinks.core": (
        "DEFAULT_ADVISORY_SUBJECTS",
        "ConsumerDrift",
        "ConsumerManagementResult",
        "InMemoryMetrics",
        "CUSTODY_SCHEMA",
        "CUSTODY_SUPPORTED_ALGORITHMS",
        "JetStreamAdvisory",
        "JetStreamAdvisoryMonitor",
        "JetStreamSinkRunner",
        "JsonFileMetrics",
        "MESSAGE_AUTHENTICITY_SCHEMA",
        "MessageAuthenticityEvaluation",
        "MessageAuthenticityViolation",
        "MetricsConfig",
        "MetricNames",
        "NatsEnvelope",
        "NoopMetrics",
        "PayloadEncryptor",
        "PayloadKeyRegistry",
        "PolicyEvaluation",
        "PolicyViolation",
        "FANOUT_OPTIONAL_ACK_DEFAULTS",
        "FanoutAckGateError",
        "FanoutAckGateResult",
        "FanoutRequiredSinkError",
        "FanoutSink",
        "FanoutTargetResult",
        "PushConsumerCapabilityResult",
        "PushConsumerConfig",
        "RouteHeaderMatchConfig",
        "RouteMatchConfig",
        "RoutePolicyRouteConfig",
        "RouteSelection",
        "RouteTargetConfig",
        "RoutingMatchPolicyConfig",
        "SizePolicyEvaluation",
        "SizePolicyViolation",
        "SECURITY_LABEL_PROFILE_NAME",
        "SUPPORTED_MESSAGE_AUTHENTICITY_ALGORITHMS",
        "SubjectPayloadEncryptor",
        "advisory_kind_from_subject",
        "attach_custody_metadata",
        "build_consumer_config",
        "build_push_consumer_config",
        "build_nats_metadata_snapshot",
        "canonical_json_bytes",
        "canonical_message_authenticity_bytes",
        "canonical_message_authenticity_document",
        "compute_custody_metadata",
        "detect_consumer_drift",
        "detect_push_consumer_capabilities",
        "detect_push_consumer_drift",
        "datetime_to_epoch_ns",
        "decrypt_payload",
        "ensure_jetstream_consumer",
        "ensure_jetstream_push_consumer",
        "evaluate_message_authenticity",
        "evaluate_pre_sink_policy",
        "evaluate_size_policy",
        "is_encrypted_payload_envelope",
        "hmac_sha256_signature_b64",
        "load_metrics_snapshot",
        "metric_rows_from_snapshot",
        "normalize_payload_for_json_storage",
        "observe_jetstream_advisory_message",
        "parse_mission_metadata_header",
        "parse_jetstream_advisory",
        "parse_security_label_header",
        "qualified_metric_name",
        "record_event_freshness_metrics",
        "route_matches_envelope",
        "select_route_targets",
        "validate_advisory_subject",
        "validate_metric_namespace",
        "validate_push_consumer_capabilities",
        "wait_for_fanout_ack_gate",
        "write_metrics_snapshot",
    ),
    "nats_sinks.file": (
        "FileCompression",
        "FileDuplicatePolicy",
        "FileFilenameStrategy",
        "FileSink",
        "FileSinkConfig",
        "FileWriteMode",
    ),
    "nats_sinks.coherence": (
        "COHERENCE_EVENT_SCHEMA",
        "COHERENCE_EVENT_SCHEMA_VERSION",
        "CoherenceDuplicatePolicy",
        "CoherenceDurabilityMode",
        "CoherenceKeyStrategy",
        "CoherenceSerializer",
        "CoherenceSessionFactory",
        "CoherenceSink",
        "CoherenceSinkConfig",
        "CoherenceStorageKind",
        "coherence_key_for_envelope",
        "coherence_value_for_envelope",
    ),
    "nats_sinks.oracle_nosql": (
        "ORACLE_NOSQL_EVENT_SCHEMA",
        "ORACLE_NOSQL_EVENT_SCHEMA_VERSION",
        "OracleNoSqlAuthMode",
        "OracleNoSqlClient",
        "OracleNoSqlClientFactory",
        "OracleNoSqlDeploymentMode",
        "OracleNoSqlDuplicatePolicy",
        "OracleNoSqlDurabilityMode",
        "OracleNoSqlKeyStrategy",
        "OracleNoSqlSink",
        "OracleNoSqlSinkConfig",
        "oracle_nosql_create_table_statement",
        "oracle_nosql_key_for_envelope",
        "oracle_nosql_row_for_envelope",
        "oracle_nosql_value_for_envelope",
    ),
    "nats_sinks.oracle": (
        "LINEAGE_FIELD_SPECS",
        "OracleLineageQuery",
        "OracleLineageReader",
        "OracleLineageRecord",
        "OracleLineageResult",
        "OracleSink",
        "OracleSinkConfig",
        "build_oracle_lineage_query",
        "render_lineage_result_text",
        "resolve_lineage_table",
    ),
    "nats_sinks.mysql": (
        "MySqlColumnMapping",
        "MySqlIdempotencyConfig",
        "MySqlSink",
        "MySqlSinkConfig",
        "MySqlTableRoute",
        "MySqlWriteMode",
    ),
    "nats_sinks.spool": (
        "SPOOL_RECORD_SCHEMA",
        "SPOOL_RECORD_VERSION",
        "SPOOL_WRAPPER_SCHEMA",
        "SPOOL_WRAPPER_VERSION",
        "SpoolDrainOrdering",
        "SpoolDuplicatePolicy",
        "SpoolReplayResult",
        "SpoolSink",
        "SpoolSinkConfig",
        "build_plain_record",
        "envelope_from_plain_record",
        "priority_rank",
        "replay_spool_to_sink",
        "spool_filename_for_envelope",
        "unwrap_record",
        "wrap_record",
    ),
    "nats_sinks.foundry": (
        "FoundryAuthMode",
        "FoundryPreparedBatch",
        "FoundryRecordKeyStrategy",
        "FoundryRecordWrapper",
        "FoundrySink",
        "FoundrySinkConfig",
        "FoundryStreamClient",
        "FoundryStreamPushResult",
        "FoundryTarget",
        "HttpFoundryStreamClient",
        "foundry_record_for_envelope",
        "foundry_record_key",
        "foundry_value_for_envelope",
        "prepare_foundry_batch",
    ),
    "nats_sinks.gotham": (
        "GothamAuthMode",
        "GothamExternalIdStrategy",
        "GothamObjectClient",
        "GothamObjectWrite",
        "GothamObjectWriteResult",
        "GothamPreparedBatch",
        "GothamSink",
        "GothamSinkConfig",
        "GothamTarget",
        "GothamValidationMode",
        "HttpGothamObjectClient",
        "gotham_external_id",
        "gotham_object_request_for_envelope",
        "prepare_gotham_batch",
    ),
    "nats_sinks.observability": (
        "AZURE_MONITOR_PROFILE_NAME",
        "AzureMonitorExportResult",
        "AzureMonitorObservabilityPolicy",
        "CLOUDWATCH_PROFILE_NAME",
        "CloudWatchExportResult",
        "CloudWatchObservabilityPolicy",
        "DATADOG_PROFILE_NAME",
        "DISABLED_AZURE_MONITOR_TEXT",
        "DISABLED_CLOUDWATCH_TEXT",
        "DISABLED_DATADOG_TEXT",
        "DISABLED_ELASTIC_TEXT",
        "DISABLED_GRAFANA_ALLOY_TEXT",
        "DISABLED_OCI_MONITORING_TEXT",
        "NATS_MONITORING_ALLOWED_ENDPOINTS",
        "NATS_MONITORING_SNAPSHOT_SCHEMA",
        "DISABLED_STATSD_TEXT",
        "DISABLED_SYSLOG_TEXT",
        "ELASTIC_OTLP_SCOPE_NAME",
        "EMPTY_AZURE_MONITOR_TEXT",
        "EMPTY_CLOUDWATCH_TEXT",
        "EMPTY_DATADOG_TEXT",
        "EMPTY_ELASTIC_TEXT",
        "EMPTY_GRAFANA_ALLOY_TEXT",
        "EMPTY_OCI_MONITORING_TEXT",
        "EMPTY_STATSD_TEXT",
        "EMPTY_SYSLOG_TEXT",
        "GRAFANA_ALLOY_OTLP_SCOPE_NAME",
        "LABELED_METRICS_SNAPSHOT_KEY",
        "OBSERVABILITY_POLICY_SCHEMA",
        "OCI_MONITORING_PROFILE_NAME",
        "STATSD_PROFILE_NAME",
        "SUBJECT_FAMILY_LABEL_NAME",
        "SYSLOG_PROFILE_NAME",
        "DatadogExportResult",
        "DatadogObservabilityPolicy",
        "ElasticObservabilityPolicy",
        "GrafanaAlloyObservabilityPolicy",
        "NatsMonitoringEndpointObservation",
        "NatsMonitoringError",
        "NatsServerMonitoringPolicy",
        "OciMonitoringExportResult",
        "OciMonitoringObservabilityPolicy",
        "ObservabilityPolicy",
        "ObservabilitySubjectPolicy",
        "OtlpExportResult",
        "OtlpMetricsPolicy",
        "PrometheusHttpEndpointPolicy",
        "PrometheusHttpResponse",
        "PrometheusTextfilePolicy",
        "SubjectAwareDecision",
        "SubjectAwareObservabilityPolicy",
        "SubjectAwareRule",
        "SubjectFamilyAggregationResult",
        "aggregate_subject_family_counter",
        "attach_labeled_metric_rows",
        "azure_monitor_metrics_endpoint",
        "build_azure_monitor_metric_documents",
        "build_azure_monitor_metric_requests",
        "build_boto3_cloudwatch_client",
        "build_cloudwatch_metric_data",
        "build_cloudwatch_put_metric_data_requests",
        "build_datadog_datagrams",
        "build_elastic_otlp_metrics_document",
        "build_grafana_alloy_otlp_metrics_document",
        "build_nats_monitoring_url",
        "build_oci_monitoring_client",
        "build_oci_monitoring_metric_data",
        "build_oci_monitoring_post_metric_data_details_model",
        "build_oci_monitoring_post_metric_data_requests",
        "build_otlp_metrics_document",
        "build_prometheus_http_server",
        "build_policy_from_app_config",
        "build_splunk_hec_event",
        "collect_nats_monitoring_snapshot",
        "ensure_azure_monitor_enabled",
        "ensure_cloudwatch_enabled",
        "ensure_datadog_enabled",
        "ensure_elastic_enabled",
        "ensure_grafana_alloy_enabled",
        "ensure_nats_monitoring_enabled",
        "ensure_oci_monitoring_enabled",
        "ensure_otlp_enabled",
        "ensure_prometheus_http_enabled",
        "ensure_splunk_hec_enabled",
        "extract_nats_monitoring_fields",
        "export_azure_monitor_metrics",
        "export_cloudwatch_metrics",
        "export_datadog_metrics",
        "export_elastic_observability_metrics",
        "export_grafana_alloy_metrics",
        "export_oci_monitoring_metrics",
        "export_otlp_metrics",
        "export_splunk_hec_metrics",
        "evaluate_subject_observability_policy",
        "filter_azure_monitor_metric_rows",
        "filter_cloudwatch_metric_rows",
        "filter_datadog_metric_rows",
        "filter_elastic_metric_rows",
        "filter_grafana_alloy_metric_rows",
        "filter_metric_rows",
        "filter_oci_monitoring_metric_rows",
        "filter_otlp_metric_rows",
        "filter_splunk_hec_metric_rows",
        "load_nats_monitoring_snapshot",
        "load_observability_policy",
        "observability_policy_template",
        "render_azure_monitor_metric_requests_json",
        "render_cloudwatch_put_metric_data_requests_json",
        "render_datadog_lines",
        "render_elastic_otlp_metrics_json",
        "render_grafana_alloy_config",
        "render_grafana_alloy_otlp_metrics_json",
        "render_nats_monitoring_prometheus",
        "render_oci_monitoring_post_metric_data_requests_json",
        "render_otlp_metrics_json",
        "render_prometheus_http_response",
        "render_prometheus_textfile",
        "render_splunk_hec_event_json",
        "resolve_azure_monitor_headers",
        "resolve_elastic_headers",
        "resolve_grafana_alloy_headers",
        "resolve_otlp_headers",
        "resolve_splunk_hec_headers",
        "serve_prometheus_http",
        "datadog_metric_name",
        "SplunkHecExportResult",
        "SplunkHecObservabilityPolicy",
        "StatsdExportResult",
        "StatsdObservabilityPolicy",
        "SyslogExportResult",
        "SyslogObservabilityPolicy",
        "build_statsd_datagrams",
        "build_syslog_datagrams",
        "build_syslog_message",
        "write_nats_monitoring_snapshot",
        "write_observability_policy",
        "write_prometheus_textfile",
        "ensure_statsd_enabled",
        "ensure_syslog_enabled",
        "export_statsd_metrics",
        "export_syslog_metrics",
        "filter_statsd_metric_rows",
        "filter_syslog_metric_rows",
        "render_statsd_lines",
        "render_syslog_messages",
        "statsd_metric_name",
    ),
    "nats_sinks.sinks": (
        "FlushableSink",
        "HealthCheckableSink",
        "SINK_CONNECTOR_API_VERSION",
        "SINK_CONNECTOR_ENTRY_POINT_GROUP",
        "SchemaAwareSink",
        "Sink",
        "SinkConnector",
        "SinkConnectorStatus",
        "SinkFactory",
        "SinkRegistry",
        "load_entry_point_connectors",
        "normalize_connector_name",
    ),
    "nats_sinks.testing": (
        "FanoutAckProbe",
        "FanoutCertificationCase",
        "FanoutCertificationResult",
        "FanoutOperationPlan",
        "SUBJECT_OBSERVABILITY_ALLOWED_LABEL",
        "SUBJECT_OBSERVABILITY_OVERFLOW_LABEL",
        "SUBJECT_OBSERVABILITY_RAW_SUBJECTS",
        "SinkCertificationCase",
        "SubjectObservabilityCertificationReport",
        "SubjectObservabilityDeliveryProbe",
        "assert_envelope_has_no_ack_primitives",
        "assert_log_records_exclude_sensitive_values",
        "assert_sink_protocol_boundary",
        "assert_subject_observability_output_is_sanitized",
        "certification_envelope",
        "certify_fanout_ack_order",
        "certify_fanout_route_selection",
        "certify_sink_duplicate_redelivery",
        "certify_sink_lifecycle",
        "certify_sink_write_success",
        "certify_subject_observability_delivery_non_interference",
        "certify_subject_observability_malformed_policy_rejection",
        "fanout_certification_envelope",
        "fanout_certification_policy",
        "render_subject_observability_connector_outputs",
        "run_subject_observability_certification",
        "subject_observability_certification_envelopes",
        "subject_observability_certification_policy",
        "subject_observability_certification_snapshot",
        "subject_observability_fail_closed_policy",
        "subject_observability_overflow_policy",
    ),
}

DOCUMENTED_IMPORT_CONTRACT: dict[str, tuple[str, ...]] = {
    **PUBLIC_API_CONTRACT,
    "nats_sinks.cli.main": ("app",),
    "nats_sinks.cli.metrics": ("app",),
    "nats_sinks.cli.observability": ("app",),
    "nats_sinks.core.config": (
        "AppConfig",
        "ConsumerManagementConfig",
        "CustodyConfig",
        "DeliveryConfig",
        "JetStreamAdvisoryConfig",
        "MissionMetadataConfig",
        "MissionMetadataRuleConfig",
        "MessageAuthenticityConfig",
        "MessageAuthenticityRuleConfig",
        "NatsConfig",
        "PreSinkPolicyConfig",
        "PreSinkPolicyRuleConfig",
        "RouteHeaderMatchConfig",
        "RouteMatchConfig",
        "RoutePolicyRouteConfig",
        "RouteTargetConfig",
        "RoutingMatchPolicyConfig",
        "SecurityLabelProfileConfig",
        "SecurityLabelRuleConfig",
        "SinkPluginConfig",
        "SizePolicyConfig",
        "load_config",
        "redacted_config",
    ),
}

STABLE_CONSOLE_SCRIPTS: dict[str, str] = {
    "nats-sink": "nats_sinks.cli.main:app",
    "nats-sink-metrics": "nats_sinks.cli.metrics:app",
    "nats-sink-observe": "nats_sinks.cli.observability:app",
}


def _pyproject() -> dict[str, object]:
    pyproject_path = Path(__file__).resolve().parents[2] / "pyproject.toml"
    return tomllib.loads(pyproject_path.read_text(encoding="utf-8"))


def _project_table() -> dict[str, Any]:
    return cast(dict[str, Any], _pyproject()["project"])


def test_documented_public_imports_remain_available() -> None:
    """Every documented module-level symbol in the contract can be imported."""

    for module_name, symbol_names in DOCUMENTED_IMPORT_CONTRACT.items():
        module = importlib.import_module(module_name)
        for symbol_name in symbol_names:
            assert getattr(module, symbol_name, None) is not None, f"{module_name}.{symbol_name}"


def test_public_exports_include_documented_contract() -> None:
    """`__all__` should include documented symbols for star-import users.

    Star imports are not the recommended style, but `__all__` is still useful
    for documentation tools, static analysis, and maintainers who want to see
    the intended public surface of a module.
    """

    for module_name, symbol_names in PUBLIC_API_CONTRACT.items():
        module = importlib.import_module(module_name)
        exported = set(getattr(module, "__all__", ()))
        assert set(symbol_names).issubset(exported), module_name


def test_public_api_smoke_imports_match_readme_examples() -> None:
    """The common README imports should keep working exactly as published."""

    assert ReadmeJetStreamSinkRunner is nats_sinks.JetStreamSinkRunner
    assert ReadmeNatsEnvelope is nats_sinks.NatsEnvelope
    assert ReadmeSink is nats_sinks.Sink
    assert ReadmeCoherenceSink is nats_sinks.CoherenceSink
    assert ReadmeFileSink is nats_sinks.FileSink
    assert ReadmeMySqlSink.__name__ == "MySqlSink"
    assert ReadmeOracleNoSqlSink is nats_sinks.OracleNoSqlSink
    assert ReadmeOracleSink.__name__ == "OracleSink"
    assert ReadmeSpoolSink is nats_sinks.SpoolSink


def test_public_metric_helper_contract_remains_stable() -> None:
    assert (
        nats_sinks.qualified_metric_name("messages_fetched_total")
        == "nats_sinks_messages_fetched_total"
    )


def test_console_script_entry_points_remain_stable() -> None:
    """PyPI users rely on the CLI command names published in metadata."""

    scripts = _project_table()["scripts"]

    assert scripts == STABLE_CONSOLE_SCRIPTS
    for entry_point in STABLE_CONSOLE_SCRIPTS.values():
        module_name, object_name = entry_point.split(":", maxsplit=1)
        command = getattr(importlib.import_module(module_name), object_name)
        assert isinstance(command, typer.Typer)


def test_runtime_version_matches_project_metadata() -> None:
    assert nats_sinks.__version__ == _project_table()["version"]
