apiVersion: v1
kind: Service
metadata:
  name: nats-sink-prometheus-http
  namespace: nats-sinks
  labels:
    app.kubernetes.io/name: nats-sinks
    app.kubernetes.io/component: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nats-sinks
    app.kubernetes.io/component: worker-with-observability
  ports:
    - name: metrics
      port: 9108
      targetPort: metrics
      protocol: TCP
