apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-sink-worker
  namespace: nats-sinks
  labels:
    app.kubernetes.io/name: nats-sinks
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
